app:
  gpuAcceleration: true
  devTools: false
  closeAction: 2
frontend:
  devPort: 3000
  host: 127.0.0.1
logging:
  level: info
  format: "[{y}-{m}-{d} {h}:{i}:{s}.{ms}] [{level}] {text}"
  keepDays: 25
network:
  proxyMode: system
  proxyUrl: ""
cache:
  dir: ""
  page:
    enabled: true
    maxSizeMB: 256
    ttlMinutes: 360
    searchTtlMinutes: 30
  playback:
    enabled: true
    maxSizeMB: 64
    maxEntries: 100
    urlTtlMinutes: 30
    lyricTtlMinutes: 1440
discord:
  enabled: true
  applicationId: "1536959813114658836"
updater:
  checkOnStartup: true
  autoDownload: false
