apiVersion: apps/v1
kind: Deployment
metadata:
  name: netease-api
  labels:
    app: netease-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netease-api
  template:
    metadata:
      labels:
        app: netease-api
    spec:
      containers:
        - name: netease-api
          image: netease-api:v1.0.0
          imagePullPolicy: IfNotPresent # 优先使用本地镜像
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
