apiVersion: v1
kind: Service
metadata:
  name: netease-api-svc
spec:
  selector:
    app: netease-api
  type: NodePort
  ports:
    - name: netease-api-svc
      port: 3000
      targetPort: 3000
      nodePort: 31212
