import type {
  ThemeSourceDefinition,
  ThemeTokenDefinition,
  ThemeTokenKind,
} from "@/types/theme-lab";

const token = (
  name: ThemeTokenDefinition["name"],
  label: string,
  group: string,
  layer: ThemeTokenDefinition["layer"],
  kind: ThemeTokenKind = "color",
  shared = false,
): ThemeTokenDefinition => ({ group, kind, label, layer, name, shared });

export const SHADCN_THEME_TOKENS = [
  token("--primary", "Background", "Primary", "shadcn"),
  token("--primary-foreground", "Foreground", "Primary", "shadcn"),
  token("--secondary", "Background", "Secondary", "shadcn"),
  token("--secondary-foreground", "Foreground", "Secondary", "shadcn"),
  token("--accent", "Background", "Accent", "shadcn"),
  token("--accent-foreground", "Foreground", "Accent", "shadcn"),
  token("--background", "Background", "Base", "shadcn"),
  token("--foreground", "Foreground", "Base", "shadcn"),
  token("--card", "Background", "Card", "shadcn"),
  token("--card-foreground", "Foreground", "Card", "shadcn"),
  token("--popover", "Background", "Popover", "shadcn"),
  token("--popover-foreground", "Foreground", "Popover", "shadcn"),
  token("--muted", "Background", "Muted", "shadcn"),
  token("--muted-foreground", "Foreground", "Muted", "shadcn"),
  token("--destructive", "Background", "Destructive", "shadcn"),
  token("--destructive-foreground", "Foreground", "Destructive", "shadcn"),
  token("--border", "Border", "Border & Input", "shadcn"),
  token("--input", "Input", "Border & Input", "shadcn"),
  token("--ring", "Ring", "Border & Input", "shadcn"),
  token("--chart-1", "Chart 1", "Chart", "shadcn"),
  token("--chart-2", "Chart 2", "Chart", "shadcn"),
  token("--chart-3", "Chart 3", "Chart", "shadcn"),
  token("--chart-4", "Chart 4", "Chart", "shadcn"),
  token("--chart-5", "Chart 5", "Chart", "shadcn"),
  token("--sidebar", "Background", "Sidebar", "shadcn"),
  token("--sidebar-foreground", "Foreground", "Sidebar", "shadcn"),
  token("--sidebar-primary", "Primary", "Sidebar", "shadcn"),
  token("--sidebar-primary-foreground", "Primary FG", "Sidebar", "shadcn"),
  token("--sidebar-accent", "Accent", "Sidebar", "shadcn"),
  token("--sidebar-accent-foreground", "Accent FG", "Sidebar", "shadcn"),
  token("--sidebar-border", "Border", "Sidebar", "shadcn"),
  token("--sidebar-ring", "Ring", "Sidebar", "shadcn"),
  token("--radius", "Radius", "Shape", "shadcn", "dimension", true),
] as const satisfies readonly ThemeTokenDefinition[];

export const SCOPIFY_THEME_TOKENS = [
  token("--scopify-font-ui", "界面字体", "字体", "scopify", "font", true),
  token("--scopify-font-code", "代码字体", "字体", "scopify", "font", true),
  token("--scopify-font-reading", "阅读字体", "字体", "scopify", "font", true),
  token("--scopify-surface-inverse", "反色表面", "产品语义", "scopify"),
  token("--scopify-content-subtle", "次弱文字", "产品语义", "scopify"),
  token("--scopify-brand-hover", "品牌悬停", "产品语义", "scopify"),
  token("--scopify-success", "成功", "状态", "scopify"),
  token("--scopify-success-foreground", "成功前景", "状态", "scopify"),
  token("--scopify-info", "信息", "状态", "scopify"),
  token("--scopify-info-foreground", "信息前景", "状态", "scopify"),
  token("--scopify-warning", "警告", "状态", "scopify"),
  token("--scopify-warning-foreground", "警告前景", "状态", "scopify"),
  token("--scopify-danger-foreground", "危险前景", "状态", "scopify"),
  token("--scopify-overlay", "页面遮罩", "遮罩", "scopify"),
  token("--scopify-overlay-foreground", "遮罩前景", "遮罩", "scopify"),
  token("--scopify-media-overlay", "媒体遮罩", "遮罩", "scopify"),
  token("--scopify-image-scrim", "图片压暗", "遮罩", "scopify"),
  token("--scopify-hero-shade", "Hero 色调", "遮罩", "scopify"),
  token("--scopify-hero-transition-depth", "Hero 过渡深度", "尺寸", "scopify", "dimension"),
  token("--scopify-calendar-surface", "日历表面", "日历", "scopify"),
  token("--scopify-calendar-surface-muted", "日历弱化表面", "日历", "scopify"),
  token("--scopify-calendar-ink", "日历文字", "日历", "scopify"),
  token("--scopify-calendar-accent", "日历强调", "日历", "scopify"),
  token("--scopify-calendar-accent-hover", "日历强调悬停", "日历", "scopify"),
  token("--scopify-calendar-divider", "日历分割线", "日历", "scopify"),
  token("--scopify-calendar-shadow", "日历阴影", "日历", "scopify", "shadow"),
  token("--scopify-qr-surface", "二维码底色", "产品语义", "scopify"),
  token("--scopify-home-atmosphere-night", "深夜氛围", "首页氛围", "scopify"),
  token("--scopify-home-atmosphere-dawn", "黎明氛围", "首页氛围", "scopify"),
  token("--scopify-home-atmosphere-morning", "早晨氛围", "首页氛围", "scopify"),
  token("--scopify-home-atmosphere-afternoon", "午后氛围", "首页氛围", "scopify"),
  token("--scopify-home-atmosphere-daylight", "日光氛围", "首页氛围", "scopify"),
  token("--scopify-home-atmosphere-sunset", "日落氛围", "首页氛围", "scopify"),
  token("--scopify-home-atmosphere-evening", "傍晚氛围", "首页氛围", "scopify"),
  token("--scopify-home-atmosphere-late-night", "午夜氛围", "首页氛围", "scopify"),
  token("--scopify-page-accent-recent", "最近播放强调", "产品语义", "scopify"),
  token("--scopify-skeleton", "骨架屏", "反馈", "scopify"),
  token("--scopify-skeleton-subtle", "弱骨架屏", "反馈", "scopify"),
  token("--scopify-scrollbar-thumb", "滚动条", "反馈", "scopify"),
  token("--scopify-scrollbar-thumb-hover", "滚动条悬停", "反馈", "scopify"),
  token("--scopify-elevation-panel", "面板阴影", "阴影", "scopify", "shadow"),
  token("--scopify-elevation-floating", "浮层阴影", "阴影", "scopify", "shadow"),
  token("--scopify-elevation-brand", "品牌阴影", "阴影", "scopify", "shadow"),
] as const satisfies readonly ThemeTokenDefinition[];

export const THEME_SOURCE_IDS = {
  scopify: "scopify-default",
  shadcn: "shadcn-default",
} as const;

export const BUILT_IN_THEME_SOURCES = [
  {
    definitions: SHADCN_THEME_TOKENS,
    id: THEME_SOURCE_IDS.shadcn,
    name: "Shadcn Default",
  },
  {
    definitions: [...SHADCN_THEME_TOKENS, ...SCOPIFY_THEME_TOKENS],
    id: THEME_SOURCE_IDS.scopify,
    name: "Scopify Default",
  },
] as const satisfies readonly ThemeSourceDefinition[];
