// This file is auto-generated by script/generate-i18n-types.ts.
// Do not edit manually.

import type { TranslationKey, TranslationParams } from "@/lib/i18n";

export interface TranslateFn {
  /**
   * zh-CN: 简体中文
   * zh-TW: 简体中文
   * en-US: Simplified Chinese
   */
  (key: "common.language.simplifiedChinese", params?: TranslationParams): string;
  /**
   * zh-CN: 繁體中文
   * zh-TW: 繁體中文
   * en-US: Traditional Chinese
   */
  (key: "common.language.traditionalChinese", params?: TranslationParams): string;
  /**
   * zh-CN: English
   * zh-TW: English
   * en-US: English
   */
  (key: "common.language.english", params?: TranslationParams): string;
  /**
   * zh-CN: 确认
   * zh-TW: 確認
   * en-US: Confirm
   */
  (key: "common.action.confirm", params?: TranslationParams): string;
  /**
   * zh-CN: 取消
   * zh-TW: 取消
   * en-US: Cancel
   */
  (key: "common.action.cancel", params?: TranslationParams): string;
  /**
   * zh-CN: 保存
   * zh-TW: 儲存
   * en-US: Save
   */
  (key: "common.action.save", params?: TranslationParams): string;
  /**
   * zh-CN: 保存中...
   * zh-TW: 儲存中...
   * en-US: Saving...
   */
  (key: "common.action.saving", params?: TranslationParams): string;
  /**
   * zh-CN: 重试
   * zh-TW: 重試
   * en-US: Retry
   */
  (key: "common.action.retry", params?: TranslationParams): string;
  /**
   * zh-CN: 重新加载
   * zh-TW: 重新載入
   * en-US: Reload
   */
  (key: "common.action.reload", params?: TranslationParams): string;
  /**
   * zh-CN: 刷新
   * zh-TW: 重新整理
   * en-US: Refresh
   */
  (key: "common.action.refresh", params?: TranslationParams): string;
  /**
   * zh-CN: 登录
   * zh-TW: 登入
   * en-US: Login
   */
  (key: "common.action.login", params?: TranslationParams): string;
  /**
   * zh-CN: 退出登录
   * zh-TW: 登出
   * en-US: Logout
   */
  (key: "common.action.logout", params?: TranslationParams): string;
  /**
   * zh-CN: 关闭
   * zh-TW: 關閉
   * en-US: Close
   */
  (key: "common.action.close", params?: TranslationParams): string;
  /**
   * zh-CN: 搜索
   * zh-TW: 搜尋
   * en-US: Search
   */
  (key: "common.action.search", params?: TranslationParams): string;
  /**
   * zh-CN: 清空
   * zh-TW: 清空
   * en-US: Clear All
   */
  (key: "common.action.clearAll", params?: TranslationParams): string;
  /**
   * zh-CN: 查看全部
   * zh-TW: 查看全部
   * en-US: View All
   */
  (key: "common.action.viewAll", params?: TranslationParams): string;
  /**
   * zh-CN: 查看全部
   * zh-TW: 查看全部
   * en-US: See all
   */
  (key: "common.action.seeAll", params?: TranslationParams): string;
  /**
   * zh-CN: 展开全部
   * zh-TW: 展開全部
   * en-US: Show all
   */
  (key: "common.action.showAll", params?: TranslationParams): string;
  /**
   * zh-CN: 收起
   * zh-TW: 收起
   * en-US: Show less
   */
  (key: "common.action.showLess", params?: TranslationParams): string;
  /**
   * zh-CN: 选择
   * zh-TW: 選擇
   * en-US: Select
   */
  (key: "common.action.select", params?: TranslationParams): string;
  /**
   * zh-CN: 关注
   * zh-TW: 關注
   * en-US: Follow
   */
  (key: "common.action.follow", params?: TranslationParams): string;
  /**
   * zh-CN: 已关注
   * zh-TW: 已關注
   * en-US: Following
   */
  (key: "common.action.following", params?: TranslationParams): string;
  /**
   * zh-CN: 回复
   * zh-TW: 回覆
   * en-US: Reply
   */
  (key: "common.action.reply", params?: TranslationParams): string;
  /**
   * zh-CN: 发布
   * zh-TW: 發佈
   * en-US: Publish
   */
  (key: "common.action.publish", params?: TranslationParams): string;
  /**
   * zh-CN: 举报
   * zh-TW: 檢舉
   * en-US: Report
   */
  (key: "common.action.report", params?: TranslationParams): string;
  /**
   * zh-CN: 删除
   * zh-TW: 刪除
   * en-US: Delete
   */
  (key: "common.action.delete", params?: TranslationParams): string;
  /**
   * zh-CN: 喜欢
   * zh-TW: 喜歡
   * en-US: Like
   */
  (key: "common.action.like", params?: TranslationParams): string;
  /**
   * zh-CN: 取消喜欢
   * zh-TW: 取消喜歡
   * en-US: Unlike
   */
  (key: "common.action.unlike", params?: TranslationParams): string;
  /**
   * zh-CN: 最小化
   * zh-TW: 最小化
   * en-US: Minimize
   */
  (key: "common.action.minimize", params?: TranslationParams): string;
  /**
   * zh-CN: 退出
   * zh-TW: 退出
   * en-US: Exit
   */
  (key: "common.action.exit", params?: TranslationParams): string;
  /**
   * zh-CN: 列表
   * zh-TW: 列表
   * en-US: List
   */
  (key: "common.label.list", params?: TranslationParams): string;
  /**
   * zh-CN: 单曲
   * zh-TW: 單曲
   * en-US: Track
   */
  (key: "common.label.track", params?: TranslationParams): string;
  /**
   * zh-CN: 专辑
   * zh-TW: 專輯
   * en-US: Album
   */
  (key: "common.label.album", params?: TranslationParams): string;
  /**
   * zh-CN: 歌手
   * zh-TW: 歌手
   * en-US: Artists
   */
  (key: "common.label.artists", params?: TranslationParams): string;
  /**
   * zh-CN: 歌手
   * zh-TW: 歌手
   * en-US: Artist
   */
  (key: "common.label.artist", params?: TranslationParams): string;
  /**
   * zh-CN: 歌单
   * zh-TW: 歌單
   * en-US: Playlists
   */
  (key: "common.label.playlists", params?: TranslationParams): string;
  /**
   * zh-CN: 歌曲
   * zh-TW: 歌曲
   * en-US: Songs
   */
  (key: "common.label.songs", params?: TranslationParams): string;
  /**
   * zh-CN: 队列
   * zh-TW: 佇列
   * en-US: Queue
   */
  (key: "common.label.queue", params?: TranslationParams): string;
  /**
   * zh-CN: 封面
   * zh-TW: 封面
   * en-US: Cover
   */
  (key: "common.label.cover", params?: TranslationParams): string;
  /**
   * zh-CN: 加载中...
   * zh-TW: 載入中...
   * en-US: Loading...
   */
  (key: "common.status.loading", params?: TranslationParams): string;
  /**
   * zh-CN: 播放中
   * zh-TW: 播放中
   * en-US: Playing
   */
  (key: "common.status.playing", params?: TranslationParams): string;
  /**
   * zh-CN: 未知歌手
   * zh-TW: 未知歌手
   * en-US: Unknown Artist
   */
  (key: "common.meta.unknownArtist", params?: TranslationParams): string;
  /**
   * zh-CN: 未知专辑
   * zh-TW: 未知專輯
   * en-US: Unknown Album
   */
  (key: "common.meta.unknownAlbum", params?: TranslationParams): string;
  /**
   * zh-CN: 未知歌曲
   * zh-TW: 未知歌曲
   * en-US: Unknown Song
   */
  (key: "common.meta.unknownSong", params?: TranslationParams): string;
  /**
   * zh-CN: 未知用户
   * zh-TW: 未知使用者
   * en-US: Unknown User
   */
  (key: "common.meta.unknownUser", params?: TranslationParams): string;
  /**
   * zh-CN: 请求失败: {{message}}
   * zh-TW: 請求失敗: {{message}}
   * en-US: Request failed: {{message}}
   */
  (key: "common.message.requestFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 操作失败: {{message}}
   * zh-TW: 操作失敗: {{message}}
   * en-US: Operation failed: {{message}}
   */
  (key: "common.message.operationFailedWithReason", params?: TranslationParams): string;
  /**
   * zh-CN: 已经到播放队列末尾了
   * zh-TW: 已經到播放佇列末尾了
   * en-US: You've reached the end of the queue
   */
  (key: "common.message.endOfQueue", params?: TranslationParams): string;
  /**
   * zh-CN: 获取歌曲播放地址或歌词失败
   * zh-TW: 取得歌曲播放位址或歌詞失敗
   * en-US: Failed to load the song stream or lyrics
   */
  (key: "common.message.playbackLoadFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 链接已复制到剪贴板
   * zh-TW: 連結已複製到剪貼簿
   * en-US: Link copied to clipboard
   */
  (key: "common.message.linkCopied", params?: TranslationParams): string;
  /**
   * zh-CN: 复制失败
   * zh-TW: 複製失敗
   * en-US: Failed to copy
   */
  (key: "common.message.copyFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 设置
   * zh-TW: 設定
   * en-US: Settings
   */
  (key: "settings.title", params?: TranslationParams): string;
  /**
   * zh-CN: 应用与显示
   * zh-TW: 應用與顯示
   * en-US: Application & Display
   */
  (key: "settings.section.application", params?: TranslationParams): string;
  /**
   * zh-CN: 日志与诊断
   * zh-TW: 日誌與診斷
   * en-US: Logging & Diagnostics
   */
  (key: "settings.section.logging", params?: TranslationParams): string;
  /**
   * zh-CN: 网络
   * zh-TW: 網路
   * en-US: Network
   */
  (key: "settings.section.network", params?: TranslationParams): string;
  /**
   * zh-CN: 后端服务
   * zh-TW: 後端服務
   * en-US: Backend Service
   */
  (key: "settings.section.backend", params?: TranslationParams): string;
  /**
   * zh-CN: 前端服务
   * zh-TW: 前端服務
   * en-US: Frontend Service
   */
  (key: "settings.section.frontend", params?: TranslationParams): string;
  /**
   * zh-CN: 界面语言
   * zh-TW: 介面語言
   * en-US: Interface Language
   */
  (key: "settings.language.label", params?: TranslationParams): string;
  /**
   * zh-CN: 支持简体中文、繁體中文和英语，默认简体中文。
   * zh-TW: 支援簡體中文、繁體中文與英文，預設為簡體中文。
   * en-US: Supports Simplified Chinese, Traditional Chinese, and English. Default is Simplified Chinese.
   */
  (key: "settings.language.sublabel", params?: TranslationParams): string;
  /**
   * zh-CN: 硬件加速
   * zh-TW: 硬體加速
   * en-US: Hardware Acceleration
   */
  (key: "settings.gpu.label", params?: TranslationParams): string;
  /**
   * zh-CN: 当应用卡顿或 GPU 兼容性较差时，可以关闭。
   * zh-TW: 當應用卡頓或 GPU 相容性較差時，可以關閉。
   * en-US: Turn this off if the app is slow or the GPU is unstable.
   */
  (key: "settings.gpu.sublabel", params?: TranslationParams): string;
  /**
   * zh-CN: 开发者工具
   * zh-TW: 開發者工具
   * en-US: Developer Tools
   */
  (key: "settings.devTools.label", params?: TranslationParams): string;
  /**
   * zh-CN: 关闭窗口行为
   * zh-TW: 關閉視窗行為
   * en-US: Window Close Action
   */
  (key: "settings.windowClose.label", params?: TranslationParams): string;
  /**
   * zh-CN: 最小化到托盘
   * zh-TW: 最小化到系統匣
   * en-US: Minimize to Tray
   */
  (key: "settings.windowClose.minimize", params?: TranslationParams): string;
  /**
   * zh-CN: 退出应用
   * zh-TW: 退出應用
   * en-US: Exit Application
   */
  (key: "settings.windowClose.exit", params?: TranslationParams): string;
  /**
   * zh-CN: 每次询问
   * zh-TW: 每次詢問
   * en-US: Ask Every Time
   */
  (key: "settings.windowClose.ask", params?: TranslationParams): string;
  /**
   * zh-CN: 日志级别
   * zh-TW: 日誌等級
   * en-US: Log Level
   */
  (key: "settings.logLevel.label", params?: TranslationParams): string;
  /**
   * zh-CN: 调试
   * zh-TW: 除錯
   * en-US: Debug
   */
  (key: "settings.logLevel.debug", params?: TranslationParams): string;
  /**
   * zh-CN: 信息
   * zh-TW: 資訊
   * en-US: Info
   */
  (key: "settings.logLevel.info", params?: TranslationParams): string;
  /**
   * zh-CN: 警告
   * zh-TW: 警告
   * en-US: Warn
   */
  (key: "settings.logLevel.warn", params?: TranslationParams): string;
  /**
   * zh-CN: 错误
   * zh-TW: 錯誤
   * en-US: Error
   */
  (key: "settings.logLevel.error", params?: TranslationParams): string;
  /**
   * zh-CN: 日志保留天数
   * zh-TW: 日誌保留天數
   * en-US: Keep Days
   */
  (key: "settings.keepDays.label", params?: TranslationParams): string;
  /**
   * zh-CN: 日志文件保留的天数。
   * zh-TW: 日誌檔案保留的天數。
   * en-US: Number of days to retain log files.
   */
  (key: "settings.keepDays.sublabel", params?: TranslationParams): string;
  /**
   * zh-CN: 超时时间 (ms)
   * zh-TW: 逾時時間 (ms)
   * en-US: Timeout (ms)
   */
  (key: "settings.timeout.label", params?: TranslationParams): string;
  /**
   * zh-CN: 请求超时时间，单位毫秒。
   * zh-TW: 請求逾時時間，單位毫秒。
   * en-US: Request timeout in milliseconds.
   */
  (key: "settings.timeout.sublabel", params?: TranslationParams): string;
  /**
   * zh-CN: 最大重试次数
   * zh-TW: 最大重試次數
   * en-US: Max Retries
   */
  (key: "settings.maxRetries.label", params?: TranslationParams): string;
  /**
   * zh-CN: 请求失败后的自动重试次数。
   * zh-TW: 請求失敗後的自動重試次數。
   * en-US: Number of times to retry a failed request.
   */
  (key: "settings.maxRetries.sublabel", params?: TranslationParams): string;
  /**
   * zh-CN: 重试间隔 (ms)
   * zh-TW: 重試間隔 (ms)
   * en-US: Retry Delay (ms)
   */
  (key: "settings.retryDelay.label", params?: TranslationParams): string;
  /**
   * zh-CN: 两次重试之间的等待时间。
   * zh-TW: 兩次重試之間的等待時間。
   * en-US: Delay between retry attempts.
   */
  (key: "settings.retryDelay.sublabel", params?: TranslationParams): string;
  /**
   * zh-CN: 随机中国 IP
   * zh-TW: 隨機中國 IP
   * en-US: Use Random CN IPs
   */
  (key: "settings.randomCNIP.label", params?: TranslationParams): string;
  /**
   * zh-CN: 用于绕过部分地域限制。
   * zh-TW: 用於繞過部分地區限制。
   * en-US: Useful for bypassing some geo restrictions.
   */
  (key: "settings.randomCNIP.sublabel", params?: TranslationParams): string;
  /**
   * zh-CN: 关闭
   * zh-TW: 關閉
   * en-US: Disabled
   */
  (key: "settings.randomCNIP.disabled", params?: TranslationParams): string;
  /**
   * zh-CN: 开启
   * zh-TW: 開啟
   * en-US: Enabled
   */
  (key: "settings.randomCNIP.enabled", params?: TranslationParams): string;
  /**
   * zh-CN: Electron 代理模式
   * zh-TW: Electron 代理模式
   * en-US: Electron Proxy Mode
   */
  (key: "settings.proxyMode.label", params?: TranslationParams): string;
  /**
   * zh-CN: 作用于 Electron 窗口资源请求；选择自定义代理时也会注入后端 API 代理参数。
   * zh-TW: 作用於 Electron 視窗資源請求；選擇自訂代理時也會注入後端 API 代理參數。
   * en-US: Applies to Electron window resource requests, and also injects backend API proxy params in custom mode.
   */
  (key: "settings.proxyMode.sublabel", params?: TranslationParams): string;
  /**
   * zh-CN: 跟随系统代理
   * zh-TW: 跟隨系統代理
   * en-US: Follow System Proxy
   */
  (key: "settings.proxyMode.system", params?: TranslationParams): string;
  /**
   * zh-CN: 不使用代理
   * zh-TW: 不使用代理
   * en-US: No Proxy
   */
  (key: "settings.proxyMode.direct", params?: TranslationParams): string;
  /**
   * zh-CN: 自定义代理
   * zh-TW: 自訂代理
   * en-US: Custom Proxy
   */
  (key: "settings.proxyMode.custom", params?: TranslationParams): string;
  /**
   * zh-CN: 代理地址
   * zh-TW: 代理位址
   * en-US: Proxy URL
   */
  (key: "settings.proxyUrl.label", params?: TranslationParams): string;
  /**
   * zh-CN: 例如 http://127.0.0.1:7890 或 socks5://127.0.0.1:7890。
   * zh-TW: 例如 http://127.0.0.1:7890 或 socks5://127.0.0.1:7890。
   * en-US: For example http://127.0.0.1:7890 or socks5://127.0.0.1:7890.
   */
  (key: "settings.proxyUrl.sublabel", params?: TranslationParams): string;
  /**
   * zh-CN: 输入代理地址
   * zh-TW: 輸入代理位址
   * en-US: Enter proxy URL
   */
  (key: "settings.proxyUrl.placeholder", params?: TranslationParams): string;
  /**
   * zh-CN: 自定义代理模式下必须填写代理地址
   * zh-TW: 自訂代理模式下必須填寫代理位址
   * en-US: A proxy URL is required when using custom proxy mode.
   */
  (key: "settings.proxyUrl.required", params?: TranslationParams): string;
  /**
   * zh-CN: 自动启动后端
   * zh-TW: 自動啟動後端
   * en-US: Auto Start Backend
   */
  (key: "settings.autoStartBackend.label", params?: TranslationParams): string;
  /**
   * zh-CN: 后端主机
   * zh-TW: 後端主機
   * en-US: Backend Host
   */
  (key: "settings.backendHost.label", params?: TranslationParams): string;
  /**
   * zh-CN: 后端端口
   * zh-TW: 後端連接埠
   * en-US: Backend Port
   */
  (key: "settings.backendPort.label", params?: TranslationParams): string;
  /**
   * zh-CN: 前端主机
   * zh-TW: 前端主機
   * en-US: Frontend Host
   */
  (key: "settings.frontendHost.label", params?: TranslationParams): string;
  /**
   * zh-CN: 开发端口
   * zh-TW: 開發埠
   * en-US: Development Port
   */
  (key: "settings.frontendPort.label", params?: TranslationParams): string;
  /**
   * zh-CN: 正在加载设置...
   * zh-TW: 正在載入設定...
   * en-US: Loading settings...
   */
  (key: "settings.loading", params?: TranslationParams): string;
  /**
   * zh-CN: 保存更改
   * zh-TW: 儲存變更
   * en-US: Save Changes
   */
  (key: "settings.save", params?: TranslationParams): string;
  /**
   * zh-CN: 确认保存
   * zh-TW: 確認儲存
   * en-US: Confirm Changes
   */
  (key: "settings.confirm.title", params?: TranslationParams): string;
  /**
   * zh-CN: 网络设置会在页面刷新后完全生效，其余设置会立即生效。
   * zh-TW: 網路設定會在重新整理頁面後完全生效，其餘設定會立即生效。
   * en-US: Network settings will take full effect after refreshing the page, while other settings will take effect immediately.
   */
  (key: "settings.confirm.subtitle.web", params?: TranslationParams): string;
  /**
   * zh-CN: 标记为“需要重启”的设置会在重启应用后完全生效，其余设置会立即生效。
   * zh-TW: 標記為「需要重啟」的設定會在重啟應用後完全生效，其餘設定會立即生效。
   * en-US: Settings marked with "Restart Required" will take full effect after restarting the application, while other settings will take effect immediately.
   */
  (key: "settings.confirm.subtitle.restart", params?: TranslationParams): string;
  /**
   * zh-CN: 确认保存更改？所有设置会立即生效。
   * zh-TW: 確認儲存變更？所有設定會立即生效。
   * en-US: Confirm saving changes? All changes will take effect immediately.
   */
  (key: "settings.confirm.subtitle.instant", params?: TranslationParams): string;
  /**
   * zh-CN: 确认
   * zh-TW: 確認
   * en-US: Confirm
   */
  (key: "settings.confirm.confirm", params?: TranslationParams): string;
  /**
   * zh-CN: 取消
   * zh-TW: 取消
   * en-US: Cancel
   */
  (key: "settings.confirm.cancel", params?: TranslationParams): string;
  /**
   * zh-CN: 需要重启
   * zh-TW: 需要重啟
   * en-US: Restart Required
   */
  (key: "settings.restartRequired", params?: TranslationParams): string;
  /**
   * zh-CN: 加载设置失败
   * zh-TW: 載入設定失敗
   * en-US: Failed to load settings
   */
  (key: "settings.loadFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 设置已保存
   * zh-TW: 設定已儲存
   * en-US: Settings saved
   */
  (key: "settings.saveSuccess", params?: TranslationParams): string;
  /**
   * zh-CN: 保存设置失败
   * zh-TW: 儲存設定失敗
   * en-US: Failed to save settings
   */
  (key: "settings.saveFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 关闭 Scopify
   * zh-TW: 關閉 Scopify
   * en-US: Close Scopify
   */
  (key: "appClose.title", params?: TranslationParams): string;
  /**
   * zh-CN: 关闭应用后，希望默认执行什么操作？
   * zh-TW: 關閉應用後，希望預設執行什麼操作？
   * en-US: What should happen by default when you close the app?
   */
  (key: "appClose.subtitle", params?: TranslationParams): string;
  /**
   * zh-CN: 最小化到托盘
   * zh-TW: 最小化到系統匣
   * en-US: Minimize to Tray
   */
  (key: "appClose.minimize", params?: TranslationParams): string;
  /**
   * zh-CN: 退出程序
   * zh-TW: 退出程式
   * en-US: Exit Application
   */
  (key: "appClose.exit", params?: TranslationParams): string;
  /**
   * zh-CN: 下次不再提示
   * zh-TW: 下次不再提示
   * en-US: Don't ask again
   */
  (key: "appClose.remember", params?: TranslationParams): string;
  /**
   * zh-CN: 正在加载 Scopify
   * zh-TW: 正在載入 Scopify
   * en-US: Loading Scopify
   */
  (key: "layout.loadingTitle", params?: TranslationParams): string;
  /**
   * zh-CN: 正在准备你的工作区...
   * zh-TW: 正在準備你的工作區...
   * en-US: Preparing your workspace...
   */
  (key: "layout.loadingDescription", params?: TranslationParams): string;
  /**
   * zh-CN: 正在启动本地服务
   * zh-TW: 正在啟動本地服務
   * en-US: Starting Local Service
   */
  (key: "layout.startingTitle", params?: TranslationParams): string;
  /**
   * zh-CN: Scopify 正在等待 Electron 后端就绪，完成后会自动进入。
   * zh-TW: Scopify 正在等待 Electron 後端就緒，完成後會自動進入。
   * en-US: Scopify is waiting for the Electron backend to become ready.
   */
  (key: "layout.startingDescription", params?: TranslationParams): string;
  /**
   * zh-CN: 本地服务启动失败
   * zh-TW: 本地服務啟動失敗
   * en-US: Local Service Failed to Start
   */
  (key: "layout.failedTitle", params?: TranslationParams): string;
  /**
   * zh-CN: 后端未能按预期启动，请重启应用后再试。
   * zh-TW: 後端未能按預期啟動，請重新啟動應用後再試。
   * en-US: The backend did not start as expected. Please restart the app and try again.
   */
  (key: "layout.failedDescription", params?: TranslationParams): string;
  /**
   * zh-CN: 重新启动应用
   * zh-TW: 重新啟動應用
   * en-US: Restart Application
   */
  (key: "layout.restartApp", params?: TranslationParams): string;
  /**
   * zh-CN: 播放
   * zh-TW: 播放
   * en-US: Play
   */
  (key: "contextMenu.play", params?: TranslationParams): string;
  /**
   * zh-CN: 暂停
   * zh-TW: 暫停
   * en-US: Pause
   */
  (key: "contextMenu.pause", params?: TranslationParams): string;
  /**
   * zh-CN: 添加到播放队列
   * zh-TW: 加入播放佇列
   * en-US: Add to Queue
   */
  (key: "contextMenu.addToQueue", params?: TranslationParams): string;
  /**
   * zh-CN: 添加到喜欢
   * zh-TW: 加入喜歡
   * en-US: Add to Liked Songs
   */
  (key: "contextMenu.addToLiked", params?: TranslationParams): string;
  /**
   * zh-CN: 从喜欢中移除
   * zh-TW: 從喜歡中移除
   * en-US: Remove from Liked Songs
   */
  (key: "contextMenu.removeFromLiked", params?: TranslationParams): string;
  /**
   * zh-CN: 添加到歌单
   * zh-TW: 加入歌單
   * en-US: Add to Playlist
   */
  (key: "contextMenu.addToPlaylist", params?: TranslationParams): string;
  /**
   * zh-CN: 评论
   * zh-TW: 評論
   * en-US: Comments
   */
  (key: "contextMenu.comments", params?: TranslationParams): string;
  /**
   * zh-CN: 复制链接
   * zh-TW: 複製連結
   * en-US: Copy Link
   */
  (key: "contextMenu.copyLink", params?: TranslationParams): string;
  /**
   * zh-CN: 从当前歌单中移除
   * zh-TW: 從目前歌單中移除
   * en-US: Remove from current playlist
   */
  (key: "contextMenu.removeFromPlaylist", params?: TranslationParams): string;
  /**
   * zh-CN: 减少推荐
   * zh-TW: 減少推薦
   * en-US: Recommend less
   */
  (key: "contextMenu.recommendLess", params?: TranslationParams): string;
  /**
   * zh-CN: 查看
   * zh-TW: 查看
   * en-US: View
   */
  (key: "contextMenu.view", params?: TranslationParams): string;
  /**
   * zh-CN: 更新歌单
   * zh-TW: 更新歌單
   * en-US: Update Playlist
   */
  (key: "contextMenu.updatePlaylist", params?: TranslationParams): string;
  /**
   * zh-CN: 删除歌单
   * zh-TW: 刪除歌單
   * en-US: Delete Playlist
   */
  (key: "contextMenu.deletePlaylist", params?: TranslationParams): string;
  /**
   * zh-CN: 复制歌单链接
   * zh-TW: 複製歌單連結
   * en-US: Copy Playlist Link
   */
  (key: "contextMenu.copyPlaylistLink", params?: TranslationParams): string;
  /**
   * zh-CN: 返回主页
   * zh-TW: 返回首頁
   * en-US: Back to Home
   */
  (key: "login.page.backHomeTitle", params?: TranslationParams): string;
  /**
   * zh-CN: 发现属于你的旋律
   * zh-TW: 發現屬於你的旋律
   * en-US: Find the melody that belongs to you
   */
  (key: "login.page.tagline", params?: TranslationParams): string;
  /**
   * zh-CN: 目前只有扫码登录可用，其他登录方式暂不可用。
   * zh-TW: 目前只有掃碼登入可用，其他登入方式暫不可用。
   * en-US: Only QR login is currently available. Other methods are temporarily unavailable.
   */
  (key: "login.page.qrOnlyNotice", params?: TranslationParams): string;
  /**
   * zh-CN: 登录失败，请检查账号信息
   * zh-TW: 登入失敗，請檢查帳號資訊
   * en-US: Login failed. Please check your account details.
   */
  (key: "login.page.loginFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 发送验证码失败
   * zh-TW: 發送驗證碼失敗
   * en-US: Failed to send verification code
   */
  (key: "login.page.sendCaptchaFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 扫码
   * zh-TW: 掃碼
   * en-US: QR
   */
  (key: "login.mode.qr", params?: TranslationParams): string;
  /**
   * zh-CN: 密码
   * zh-TW: 密碼
   * en-US: Password
   */
  (key: "login.mode.password", params?: TranslationParams): string;
  /**
   * zh-CN: 短信
   * zh-TW: 簡訊
   * en-US: SMS
   */
  (key: "login.mode.sms", params?: TranslationParams): string;
  /**
   * zh-CN: 手机号码
   * zh-TW: 手機號碼
   * en-US: Phone Number
   */
  (key: "login.form.phoneLabel", params?: TranslationParams): string;
  /**
   * zh-CN: 请输入手机号
   * zh-TW: 請輸入手機號碼
   * en-US: Enter your phone number
   */
  (key: "login.form.phonePlaceholder", params?: TranslationParams): string;
  /**
   * zh-CN: 密码
   * zh-TW: 密碼
   * en-US: Password
   */
  (key: "login.form.passwordLabel", params?: TranslationParams): string;
  /**
   * zh-CN: 请输入密码
   * zh-TW: 請輸入密碼
   * en-US: Enter your password
   */
  (key: "login.form.passwordPlaceholder", params?: TranslationParams): string;
  /**
   * zh-CN: 登录中...
   * zh-TW: 登入中...
   * en-US: Signing in...
   */
  (key: "login.form.passwordSubmitting", params?: TranslationParams): string;
  /**
   * zh-CN: 登录
   * zh-TW: 登入
   * en-US: Sign In
   */
  (key: "login.form.passwordSubmit", params?: TranslationParams): string;
  /**
   * zh-CN: 验证码
   * zh-TW: 驗證碼
   * en-US: Verification Code
   */
  (key: "login.form.captchaLabel", params?: TranslationParams): string;
  /**
   * zh-CN: 4 位验证码
   * zh-TW: 4 位驗證碼
   * en-US: 4-digit code
   */
  (key: "login.form.captchaPlaceholder", params?: TranslationParams): string;
  /**
   * zh-CN: 获取验证码
   * zh-TW: 取得驗證碼
   * en-US: Get Code
   */
  (key: "login.form.getCaptcha", params?: TranslationParams): string;
  /**
   * zh-CN: 验证中...
   * zh-TW: 驗證中...
   * en-US: Verifying...
   */
  (key: "login.form.verifying", params?: TranslationParams): string;
  /**
   * zh-CN: 验证并登录
   * zh-TW: 驗證並登入
   * en-US: Verify and Sign In
   */
  (key: "login.form.verifyAndLogin", params?: TranslationParams): string;
  /**
   * zh-CN: 正在加载二维码...
   * zh-TW: 正在載入 QR Code...
   * en-US: Loading QR code...
   */
  (key: "login.qr.loading", params?: TranslationParams): string;
  /**
   * zh-CN: 打开 App 扫一扫登录
   * zh-TW: 打開 App 掃一掃登入
   * en-US: Open the app and scan to sign in
   */
  (key: "login.qr.waiting", params?: TranslationParams): string;
  /**
   * zh-CN: 二维码已过期
   * zh-TW: QR Code 已過期
   * en-US: QR code expired
   */
  (key: "login.qr.expired", params?: TranslationParams): string;
  /**
   * zh-CN: 已扫码，请在手机上确认
   * zh-TW: 已掃碼，請在手機上確認
   * en-US: Scanned. Please confirm on your phone
   */
  (key: "login.qr.scanned", params?: TranslationParams): string;
  /**
   * zh-CN: 授权登录成功！
   * zh-TW: 授權登入成功！
   * en-US: Authorization successful!
   */
  (key: "login.qr.success", params?: TranslationParams): string;
  /**
   * zh-CN: 登录状态异常
   * zh-TW: 登入狀態異常
   * en-US: Abnormal login status
   */
  (key: "login.qr.statusError", params?: TranslationParams): string;
  /**
   * zh-CN: 网络请求失败
   * zh-TW: 網路請求失敗
   * en-US: Network request failed
   */
  (key: "login.qr.networkError", params?: TranslationParams): string;
  /**
   * zh-CN: 登录二维码
   * zh-TW: 登入 QR Code
   * en-US: Login QR code
   */
  (key: "login.qr.alt", params?: TranslationParams): string;
  /**
   * zh-CN: 正在生成...
   * zh-TW: 正在產生...
   * en-US: Generating...
   */
  (key: "login.qr.generating", params?: TranslationParams): string;
  /**
   * zh-CN: 刷新二维码
   * zh-TW: 重新整理 QR Code
   * en-US: Refresh QR code
   */
  (key: "login.qr.refresh", params?: TranslationParams): string;
  /**
   * zh-CN: 请在手机上确认
   * zh-TW: 請在手機上確認
   * en-US: Confirm on your phone
   */
  (key: "login.qr.confirmOnPhone", params?: TranslationParams): string;
  /**
   * zh-CN: 使用 网易云音乐 App 扫码
   * zh-TW: 使用 網易雲音樂 App 掃碼
   * en-US: Scan with the NetEase Cloud Music app
   */
  (key: "login.qr.scanHint", params?: TranslationParams): string;
  /**
   * zh-CN: 登录状态异常，请重新登录
   * zh-TW: 登入狀態異常，請重新登入
   * en-US: Abnormal login status. Please sign in again.
   */
  (key: "login.qr.toast.statusError", params?: TranslationParams): string;
  /**
   * zh-CN: 登录成功
   * zh-TW: 登入成功
   * en-US: Login successful
   */
  (key: "login.qr.toast.success", params?: TranslationParams): string;
  /**
   * zh-CN: 筛选
   * zh-TW: 篩選
   * en-US: Filter
   */
  (key: "sidebar.filter.title", params?: TranslationParams): string;
  /**
   * zh-CN: 歌单
   * zh-TW: 歌單
   * en-US: Playlists
   */
  (key: "sidebar.filter.playlistTitle", params?: TranslationParams): string;
  /**
   * zh-CN: 全部
   * zh-TW: 全部
   * en-US: All
   */
  (key: "sidebar.filter.all", params?: TranslationParams): string;
  /**
   * zh-CN: 创建
   * zh-TW: 建立
   * en-US: Created
   */
  (key: "sidebar.filter.created", params?: TranslationParams): string;
  /**
   * zh-CN: 收藏
   * zh-TW: 收藏
   * en-US: Subscribed
   */
  (key: "sidebar.filter.subscribed", params?: TranslationParams): string;
  /**
   * zh-CN: 创建歌单
   * zh-TW: 建立歌單
   * en-US: Create Playlist
   */
  (key: "sidebar.filter.createPlaylists", params?: TranslationParams): string;
  /**
   * zh-CN: 展开侧边栏
   * zh-TW: 展開側邊欄
   * en-US: Expand Sidebar
   */
  (key: "sidebar.filter.expand", params?: TranslationParams): string;
  /**
   * zh-CN: 加载歌单失败
   * zh-TW: 載入歌單失敗
   * en-US: Failed to load playlists
   */
  (key: "sidebar.card.loadFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 登录后查看你的歌单
   * zh-TW: 登入後查看你的歌單
   * en-US: Log in to view your playlists
   */
  (key: "sidebar.card.loginTitle", params?: TranslationParams): string;
  /**
   * zh-CN: 登录后即可查看你创建和收藏的所有歌单。
   * zh-TW: 登入後即可查看你建立與收藏的所有歌單。
   * en-US: Log in to view playlists you created and favorited.
   */
  (key: "sidebar.card.loginSubtitle", params?: TranslationParams): string;
  /**
   * zh-CN: 你还没有任何歌单
   * zh-TW: 你還沒有任何歌單
   * en-US: You don't have any playlists yet
   */
  (key: "sidebar.card.noPlaylistsTitle", params?: TranslationParams): string;
  /**
   * zh-CN: 创建歌单或在网易云音乐中收藏歌单后，这里就会显示。
   * zh-TW: 建立歌單或在網易雲音樂收藏歌單後，這裡就會顯示。
   * en-US: Create a playlist or favorite playlists on NetEase Cloud Music to see them here.
   */
  (key: "sidebar.card.noPlaylistsSubtitle", params?: TranslationParams): string;
  /**
   * zh-CN: 创建的歌单
   * zh-TW: 建立的歌單
   * en-US: Created Playlists
   */
  (key: "sidebar.group.created", params?: TranslationParams): string;
  /**
   * zh-CN: 收藏的歌单
   * zh-TW: 收藏的歌單
   * en-US: Subscribed Playlists
   */
  (key: "sidebar.group.subscribed", params?: TranslationParams): string;
  /**
   * zh-CN: 歌单 · 你
   * zh-TW: 歌單 · 你
   * en-US: Playlist • You
   */
  (key: "sidebar.playlist.you", params?: TranslationParams): string;
  /**
   * zh-CN: 歌单 · {{name}}
   * zh-TW: 歌單 · {{name}}
   * en-US: Playlist • {{name}}
   */
  (key: "sidebar.playlist.byCreator", params?: TranslationParams): string;
  /**
   * zh-CN: 专辑 · {{name}}
   * zh-TW: 專輯 · {{name}}
   * en-US: Album • {{name}}
   */
  (key: "sidebar.Album.byCreator", params?: TranslationParams): string;
  /**
   * zh-CN: 获取歌单失败，请稍后再试
   * zh-TW: 取得歌單失敗，請稍後再試
   * en-US: Failed to load playlists. Please try again later.
   */
  (key: "sidebar.toast.fetchFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 侧边栏
   * zh-TW: 側邊欄
   * en-US: Sidebar
   */
  (key: "sidebar.menu.sidebarTitle", params?: TranslationParams): string;
  /**
   * zh-CN: 歌单管理
   * zh-TW: 歌單管理
   * en-US: Playlist Management
   */
  (key: "sidebar.menu.playlistTitle", params?: TranslationParams): string;
  /**
   * zh-CN: 折叠侧边栏
   * zh-TW: 收合側邊欄
   * en-US: Collapse Sidebar
   */
  (key: "sidebar.menu.collapse", params?: TranslationParams): string;
  /**
   * zh-CN: 创建歌单
   * zh-TW: 建立歌單
   * en-US: Create Playlist
   */
  (key: "sidebar.menu.createPlaylist", params?: TranslationParams): string;
  /**
   * zh-CN: 删除歌单
   * zh-TW: 刪除歌單
   * en-US: Delete Playlist
   */
  (key: "sidebar.menu.deletePlaylist", params?: TranslationParams): string;
  /**
   * zh-CN: 确认删除歌单
   * zh-TW: 確認刪除歌單
   * en-US: Confirm Playlist Deletion
   */
  (key: "sidebar.menu.deleteConfirmTitle", params?: TranslationParams): string;
  /**
   * zh-CN: 确定要删除歌单“{{name}}”吗？此操作无法撤销。
   * zh-TW: 確定要刪除歌單「{{name}}」嗎？此操作無法復原。
   * en-US: Are you sure you want to delete the playlist "{{name}}"? This action cannot be undone.
   */
  (key: "sidebar.menu.deleteConfirmContent", params?: TranslationParams): string;
  /**
   * zh-CN: 歌单“{{name}}”已创建
   * zh-TW: 歌單「{{name}}」已建立
   * en-US: Playlist "{{name}}" has been created
   */
  (key: "sidebar.menu.createSuccess", params?: TranslationParams): string;
  /**
   * zh-CN: 创建歌单失败
   * zh-TW: 建立歌單失敗
   * en-US: Failed to create playlist
   */
  (key: "sidebar.menu.createFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 歌单“{{name}}”已删除
   * zh-TW: 歌單「{{name}}」已刪除
   * en-US: Playlist "{{name}}" has been deleted
   */
  (key: "sidebar.menu.deleteSuccess", params?: TranslationParams): string;
  /**
   * zh-CN: 删除歌单失败
   * zh-TW: 刪除歌單失敗
   * en-US: Failed to delete playlist
   */
  (key: "sidebar.menu.deleteFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 未命名歌单
   * zh-TW: 未命名歌單
   * en-US: Untitled Playlist
   */
  (key: "sidebar.lib.untitledPlaylist", params?: TranslationParams): string;
  /**
   * zh-CN: 确认删除歌单
   * zh-TW: 確認刪除歌單
   * en-US: Confirm Playlist Deletion
   */
  (key: "sidebar.lib.deleteConfirmTitle", params?: TranslationParams): string;
  /**
   * zh-CN: 确定要删除歌单“{{name}}”吗？此操作无法撤销。
   * zh-TW: 確定要刪除歌單「{{name}}」嗎？此操作無法復原。
   * en-US: Are you sure you want to delete the playlist "{{name}}"? This action cannot be undone.
   */
  (key: "sidebar.lib.deleteConfirmContent", params?: TranslationParams): string;
  /**
   * zh-CN: “{{name}}”已更新
   * zh-TW: 「{{name}}」已更新
   * en-US: "{{name}}" has been updated
   */
  (key: "sidebar.lib.updateSuccess", params?: TranslationParams): string;
  /**
   * zh-CN: 更新歌单失败
   * zh-TW: 更新歌單失敗
   * en-US: Failed to update playlist
   */
  (key: "sidebar.lib.updateFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 更新歌单时发生错误
   * zh-TW: 更新歌單時發生錯誤
   * en-US: An unexpected error occurred while updating the playlist
   */
  (key: "sidebar.lib.updateUnexpectedError", params?: TranslationParams): string;
  /**
   * zh-CN: 此歌单中没有歌曲
   * zh-TW: 此歌單中沒有歌曲
   * en-US: No tracks found in this playlist
   */
  (key: "sidebar.lib.noTracks", params?: TranslationParams): string;
  /**
   * zh-CN: 获取歌曲失败
   * zh-TW: 取得歌曲失敗
   * en-US: Failed to fetch tracks
   */
  (key: "sidebar.lib.fetchTracksFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 歌单链接已复制到剪贴板
   * zh-TW: 歌單連結已複製到剪貼簿
   * en-US: Playlist link copied to clipboard
   */
  (key: "sidebar.lib.playlistLinkCopied", params?: TranslationParams): string;
  /**
   * zh-CN: 编辑歌单信息
   * zh-TW: 編輯歌單信息
   * en-US: Edit Playlist Information
   */
  (key: "playlist.form.editTitle", params?: TranslationParams): string;
  /**
   * zh-CN: 为你的歌单添加名称
   * zh-TW: 為你的歌單新增名稱
   * en-US: Add a name for your playlist
   */
  (key: "playlist.form.namePlaceholder", params?: TranslationParams): string;
  /**
   * zh-CN: 为你的歌单添加简介
   * zh-TW: 為你的歌單新增簡介
   * en-US: Add a description for your playlist
   */
  (key: "playlist.form.descriptionPlaceholder", params?: TranslationParams): string;
  /**
   * zh-CN: 替换封面
   * zh-TW: 更換封面
   * en-US: Replace Image
   */
  (key: "playlist.form.replaceImage", params?: TranslationParams): string;
  /**
   * zh-CN: 歌单封面
   * zh-TW: 歌單封面
   * en-US: Playlist Cover
   */
  (key: "playlist.form.coverAlt", params?: TranslationParams): string;
  /**
   * zh-CN: 确认删除
   * zh-TW: 確認刪除
   * en-US: Confirm Deletion
   */
  (key: "playlist.table.confirmDeleteTitle", params?: TranslationParams): string;
  /**
   * zh-CN: 确定要将这首歌从歌单中移除吗？
   * zh-TW: 確定要將這首歌從歌單中移除嗎？
   * en-US: Are you sure you want to remove this track from the playlist?
   */
  (key: "playlist.table.confirmDeleteContent", params?: TranslationParams): string;
  /**
   * zh-CN: 标题
   * zh-TW: 標題
   * en-US: Title
   */
  (key: "playlist.table.columnTitle", params?: TranslationParams): string;
  /**
   * zh-CN: 专辑
   * zh-TW: 專輯
   * en-US: Album
   */
  (key: "playlist.table.columnAlbum", params?: TranslationParams): string;
  /**
   * zh-CN: 发布时间
   * zh-TW: 發佈時間
   * en-US: Date Published
   */
  (key: "playlist.table.columnPublished", params?: TranslationParams): string;
  /**
   * zh-CN: 喜欢
   * zh-TW: 喜歡
   * en-US: Like
   */
  (key: "playlist.table.columnLike", params?: TranslationParams): string;
  /**
   * zh-CN: 没有找到与“{{query}}”相关的歌曲
   * zh-TW: 找不到與「{{query}}」相關的歌曲
   * en-US: No songs found for "{{query}}"
   */
  (key: "playlist.table.searchNoResults", params?: TranslationParams): string;
  /**
   * zh-CN: 暂时没有请求到歌曲数据，可以再试一次。
   * zh-TW: 暫時沒有取得歌曲資料，可以再試一次。
   * en-US: No song data has been fetched yet. You can try again.
   */
  (key: "playlist.table.noFetchedData", params?: TranslationParams): string;
  /**
   * zh-CN: 暂无歌曲数据
   * zh-TW: 暫無歌曲資料
   * en-US: No song data available
   */
  (key: "playlist.table.noSongs", params?: TranslationParams): string;
  /**
   * zh-CN: 已从歌单移除
   * zh-TW: 已從歌單移除
   * en-US: Removed from playlist
   */
  (key: "playlist.table.removeSuccess", params?: TranslationParams): string;
  /**
   * zh-CN: 从歌单移除失败
   * zh-TW: 從歌單移除失敗
   * en-US: Failed to remove from playlist
   */
  (key: "playlist.table.removeFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 已标记为不喜欢
   * zh-TW: 已標記為不喜歡
   * en-US: Marked as not interested
   */
  (key: "playlist.table.dislikeSuccess", params?: TranslationParams): string;
  /**
   * zh-CN: 歌曲已在队列中
   * zh-TW: 歌曲已在佇列中
   * en-US: Song is already in the queue
   */
  (key: "playlist.table.queueExists", params?: TranslationParams): string;
  /**
   * zh-CN: 已添加到播放队列
   * zh-TW: 已加入播放佇列
   * en-US: Added to the playback queue
   */
  (key: "playlist.table.queueAdded", params?: TranslationParams): string;
  /**
   * zh-CN: 已添加到喜欢
   * zh-TW: 已加入喜歡
   * en-US: Added to Liked Songs
   */
  (key: "playlist.table.likedAdded", params?: TranslationParams): string;
  /**
   * zh-CN: 已取消喜欢
   * zh-TW: 已取消喜歡
   * en-US: Removed from Liked Songs
   */
  (key: "playlist.table.likedRemoved", params?: TranslationParams): string;
  /**
   * zh-CN: 操作失败，请稍后再试
   * zh-TW: 操作失敗，請稍後再試
   * en-US: Operation failed. Please try again later.
   */
  (key: "playlist.table.operationFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 已成功添加到歌单
   * zh-TW: 已成功加入歌單
   * en-US: Added to playlist successfully
   */
  (key: "playlist.table.addToPlaylistSuccess", params?: TranslationParams): string;
  /**
   * zh-CN: 添加到歌单失败
   * zh-TW: 加入歌單失敗
   * en-US: Failed to add to playlist
   */
  (key: "playlist.table.addToPlaylistFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 已复制
   * zh-TW: 已複製
   * en-US: Copied
   */
  (key: "playlist.table.copySuccess", params?: TranslationParams): string;
  /**
   * zh-CN: 复制失败
   * zh-TW: 複製失敗
   * en-US: Failed
   */
  (key: "playlist.table.copyFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 搜索...
   * zh-TW: 搜尋...
   * en-US: Search...
   */
  (key: "playlist.actions.searchPlaceholder", params?: TranslationParams): string;
  /**
   * zh-CN: 列表
   * zh-TW: 列表
   * en-US: List
   */
  (key: "playlist.actions.listLabel", params?: TranslationParams): string;
  /**
   * zh-CN: 已添加到喜欢的歌曲
   * zh-TW: 已加入喜歡的歌曲
   * en-US: Added to your Liked Songs
   */
  (key: "playlist.track.likedAdded", params?: TranslationParams): string;
  /**
   * zh-CN: 已从喜欢的歌曲中移除
   * zh-TW: 已從喜歡的歌曲中移除
   * en-US: Removed from your Liked Songs
   */
  (key: "playlist.track.likedRemoved", params?: TranslationParams): string;
  /**
   * zh-CN: 每日推荐
   * zh-TW: 每日推薦
   * en-US: Daily Recommendations
   */
  (key: "playlist.meta.dailyTitle", params?: TranslationParams): string;
  /**
   * zh-CN: 为你推荐
   * zh-TW: 為你推薦
   * en-US: Made For You
   */
  (key: "playlist.meta.madeForYou", params?: TranslationParams): string;
  /**
   * zh-CN: 每日
   * zh-TW: 每日
   * en-US: Daily
   */
  (key: "playlist.meta.dailyTag", params?: TranslationParams): string;
  /**
   * zh-CN: 推荐
   * zh-TW: 推薦
   * en-US: Recommendation
   */
  (key: "playlist.meta.recommendationTag", params?: TranslationParams): string;
  /**
   * zh-CN: Scopify
   * zh-TW: Scopify
   * en-US: Scopify
   */
  (key: "playlist.meta.spotify", params?: TranslationParams): string;
  /**
   * zh-CN: 公开歌单
   * zh-TW: 公開歌單
   * en-US: Public Playlist
   */
  (key: "playlist.meta.public", params?: TranslationParams): string;
  /**
   * zh-CN: 私密歌单
   * zh-TW: 私密歌單
   * en-US: Private Playlist
   */
  (key: "playlist.meta.private", params?: TranslationParams): string;
  /**
   * zh-CN: 未知权限
   * zh-TW: 未知權限
   * en-US: Unknown Privacy
   */
  (key: "playlist.meta.unknownPrivacy", params?: TranslationParams): string;
  /**
   * zh-CN: 未知
   * zh-TW: 未知
   * en-US: Unknown
   */
  (key: "playlist.meta.unknown", params?: TranslationParams): string;
  /**
   * zh-CN: 未知日期
   * zh-TW: 未知日期
   * en-US: Unknown Date
   */
  (key: "playlist.meta.unknownDate", params?: TranslationParams): string;
  /**
   * zh-CN: 无效的歌单地址
   * zh-TW: 無效的歌單網址
   * en-US: Invalid playlist URL
   */
  (key: "playlist.page.invalidUrl", params?: TranslationParams): string;
  /**
   * zh-CN: 最近搜索
   * zh-TW: 最近搜尋
   * en-US: Recent Searches
   */
  (key: "search.modal.recentSearches", params?: TranslationParams): string;
  /**
   * zh-CN: 最近搜索
   * zh-TW: 最近搜尋
   * en-US: Recent Search
   */
  (key: "search.modal.recentSearch", params?: TranslationParams): string;
  /**
   * zh-CN: 相关建议
   * zh-TW: 相關建議
   * en-US: Related Suggestions
   */
  (key: "search.modal.relatedSuggestions", params?: TranslationParams): string;
  /**
   * zh-CN: 没有找到相关内容
   * zh-TW: 沒有找到相關內容
   * en-US: No related results found
   */
  (key: "search.modal.noResults", params?: TranslationParams): string;
  /**
   * zh-CN: 最佳匹配
   * zh-TW: 最佳匹配
   * en-US: Best Match
   */
  (key: "search.section.bestMatch", params?: TranslationParams): string;
  /**
   * zh-CN: 歌曲
   * zh-TW: 歌曲
   * en-US: Songs
   */
  (key: "search.section.songs", params?: TranslationParams): string;
  /**
   * zh-CN: 歌手
   * zh-TW: 歌手
   * en-US: Artists
   */
  (key: "search.section.artists", params?: TranslationParams): string;
  /**
   * zh-CN: 专辑
   * zh-TW: 專輯
   * en-US: Albums
   */
  (key: "search.section.albums", params?: TranslationParams): string;
  /**
   * zh-CN: 歌单
   * zh-TW: 歌單
   * en-US: Playlists
   */
  (key: "search.section.playlists", params?: TranslationParams): string;
  /**
   * zh-CN: 没有匹配结果
   * zh-TW: 沒有匹配結果
   * en-US: No matching results
   */
  (key: "search.section.noMatchingResults", params?: TranslationParams): string;
  /**
   * zh-CN: 没有歌曲结果
   * zh-TW: 沒有歌曲結果
   * en-US: No song results
   */
  (key: "search.section.noSongResults", params?: TranslationParams): string;
  /**
   * zh-CN: 搜索歌曲
   * zh-TW: 搜尋歌曲
   * en-US: Search Songs
   */
  (key: "search.section.searchSongs", params?: TranslationParams): string;
  /**
   * zh-CN: 歌手
   * zh-TW: 歌手
   * en-US: Artist
   */
  (key: "search.section.artistLabel", params?: TranslationParams): string;
  /**
   * zh-CN: 来自 {{name}}
   * zh-TW: 來自 {{name}}
   * en-US: By {{name}}
   */
  (key: "search.playlist.byCreator", params?: TranslationParams): string;
  /**
   * zh-CN: 网易云用户
   * zh-TW: 網易雲使用者
   * en-US: NetEase User
   */
  (key: "search.playlist.neteaseUser", params?: TranslationParams): string;
  /**
   * zh-CN: 全部
   * zh-TW: 全部
   * en-US: All
   */
  (key: "search.category.all", params?: TranslationParams): string;
  /**
   * zh-CN: 歌曲
   * zh-TW: 歌曲
   * en-US: Songs
   */
  (key: "search.category.songs", params?: TranslationParams): string;
  /**
   * zh-CN: 歌手
   * zh-TW: 歌手
   * en-US: Artists
   */
  (key: "search.category.artists", params?: TranslationParams): string;
  /**
   * zh-CN: 歌单
   * zh-TW: 歌單
   * en-US: Playlists
   */
  (key: "search.category.playlists", params?: TranslationParams): string;
  /**
   * zh-CN: 专辑
   * zh-TW: 專輯
   * en-US: Albums
   */
  (key: "search.category.albums", params?: TranslationParams): string;
  /**
   * zh-CN: 综合搜索失败，请稍后再试
   * zh-TW: 綜合搜尋失敗，請稍後再試
   * en-US: Comprehensive search failed. Please try again.
   */
  (key: "search.hook.failedAll", params?: TranslationParams): string;
  /**
   * zh-CN: {{category}} 搜索失败
   * zh-TW: {{category}} 搜尋失敗
   * en-US: {{category}} search failed
   */
  (key: "search.hook.failedCategory", params?: TranslationParams): string;
  /**
   * zh-CN: 未知歌手
   * zh-TW: 未知歌手
   * en-US: Unknown Artist
   */
  (key: "search.song.unknownArtist", params?: TranslationParams): string;
  /**
   * zh-CN: 已点赞
   * zh-TW: 已按讚
   * en-US: Liked
   */
  (key: "comments.page.likeSuccess", params?: TranslationParams): string;
  /**
   * zh-CN: 已取消点赞
   * zh-TW: 已取消按讚
   * en-US: Like removed
   */
  (key: "comments.page.unlikeSuccess", params?: TranslationParams): string;
  /**
   * zh-CN: 评论已删除
   * zh-TW: 評論已刪除
   * en-US: Comment deleted
   */
  (key: "comments.page.deleted", params?: TranslationParams): string;
  /**
   * zh-CN: 回复成功
   * zh-TW: 回覆成功
   * en-US: Reply sent
   */
  (key: "comments.page.replySuccess", params?: TranslationParams): string;
  /**
   * zh-CN: 发布成功
   * zh-TW: 發佈成功
   * en-US: Comment published
   */
  (key: "comments.page.publishSuccess", params?: TranslationParams): string;
  /**
   * zh-CN: 请先登录后再评论
   * zh-TW: 請先登入後再評論
   * en-US: Please log in before commenting
   */
  (key: "comments.page.loginRequired", params?: TranslationParams): string;
  /**
   * zh-CN: 单曲
   * zh-TW: 單曲
   * en-US: Track
   */
  (key: "comments.page.trackTag", params?: TranslationParams): string;
  /**
   * zh-CN: 加载中...
   * zh-TW: 載入中...
   * en-US: Loading...
   */
  (key: "comments.page.loadingTrack", params?: TranslationParams): string;
  /**
   * zh-CN: 全部评论
   * zh-TW: 全部評論
   * en-US: All Comments
   */
  (key: "comments.page.allComments", params?: TranslationParams): string;
  /**
   * zh-CN: 精彩评论
   * zh-TW: 精彩評論
   * en-US: Hot Comments
   */
  (key: "comments.page.hotComments", params?: TranslationParams): string;
  /**
   * zh-CN: 最新评论
   * zh-TW: 最新評論
   * en-US: Latest Comments
   */
  (key: "comments.page.latestComments", params?: TranslationParams): string;
  /**
   * zh-CN: 还没有评论，来成为第一个评论的人吧！
   * zh-TW: 還沒有評論，來成為第一個評論的人吧！
   * en-US: No comments yet. Be the first to comment!
   */
  (key: "comments.page.noComments", params?: TranslationParams): string;
  /**
   * zh-CN: 向下滚动以加载更多...
   * zh-TW: 向下捲動以載入更多...
   * en-US: Scroll down to load more...
   */
  (key: "comments.page.loadMore", params?: TranslationParams): string;
  /**
   * zh-CN: 已经到底了！
   * zh-TW: 已經到底了！
   * en-US: Already at the bottom!
   */
  (key: "comments.page.end", params?: TranslationParams): string;
  /**
   * zh-CN: 发表评论
   * zh-TW: 發表評論
   * en-US: Add Comment
   */
  (key: "comments.page.addComment", params?: TranslationParams): string;
  /**
   * zh-CN: 回复评论
   * zh-TW: 回覆評論
   * en-US: Reply Comment
   */
  (key: "comments.page.replyComment", params?: TranslationParams): string;
  /**
   * zh-CN: 回复给:
   * zh-TW: 回覆給:
   * en-US: Replying to:
   */
  (key: "comments.page.replyingTo", params?: TranslationParams): string;
  /**
   * zh-CN: 回复 @{{name}}:
   * zh-TW: 回覆 @{{name}}:
   * en-US: Reply to @{{name}}:
   */
  (key: "comments.input.replyTo", params?: TranslationParams): string;
  /**
   * zh-CN: 取消
   * zh-TW: 取消
   * en-US: Cancel
   */
  (key: "comments.input.cancel", params?: TranslationParams): string;
  /**
   * zh-CN: 写下你的回复...
   * zh-TW: 寫下你的回覆...
   * en-US: Write your reply...
   */
  (key: "comments.input.replyPlaceholder", params?: TranslationParams): string;
  /**
   * zh-CN: 说点什么吧...
   * zh-TW: 說點什麼吧...
   * en-US: Say something...
   */
  (key: "comments.input.publishPlaceholder", params?: TranslationParams): string;
  /**
   * zh-CN: 该评论已删除。
   * zh-TW: 該評論已刪除。
   * en-US: This comment has been deleted.
   */
  (key: "comments.item.deletedComment", params?: TranslationParams): string;
  /**
   * zh-CN: 举报
   * zh-TW: 檢舉
   * en-US: Report
   */
  (key: "comments.item.report", params?: TranslationParams): string;
  /**
   * zh-CN: 删除
   * zh-TW: 刪除
   * en-US: Delete
   */
  (key: "comments.item.delete", params?: TranslationParams): string;
  /**
   * zh-CN: 播放队列
   * zh-TW: 播放佇列
   * en-US: Play Queue
   */
  (key: "queue.triggerTitle", params?: TranslationParams): string;
  /**
   * zh-CN: 当前队列
   * zh-TW: 目前佇列
   * en-US: Current Queue
   */
  (key: "queue.title", params?: TranslationParams): string;
  /**
   * zh-CN: 共 {{count}} 首
   * zh-TW: 共 {{count}} 首
   * en-US: Total Songs: {{count}}
   */
  (key: "queue.totalSongs", params?: TranslationParams): string;
  /**
   * zh-CN: 定位到当前播放
   * zh-TW: 定位到目前播放
   * en-US: Locate Current Track
   */
  (key: "queue.locateCurrent", params?: TranslationParams): string;
  /**
   * zh-CN: 队列为空
   * zh-TW: 佇列為空
   * en-US: Queue is empty
   */
  (key: "queue.empty", params?: TranslationParams): string;
  /**
   * zh-CN: 通知
   * zh-TW: 通知
   * en-US: Notifications
   */
  (key: "profile.menu.notifications", params?: TranslationParams): string;
  /**
   * zh-CN: 朋友
   * zh-TW: 朋友
   * en-US: Friends
   */
  (key: "profile.menu.friends", params?: TranslationParams): string;
  /**
   * zh-CN: 个人主页
   * zh-TW: 個人主頁
   * en-US: Profile
   */
  (key: "profile.menu.profile", params?: TranslationParams): string;
  /**
   * zh-CN: 设置
   * zh-TW: 設定
   * en-US: Settings
   */
  (key: "profile.menu.settings", params?: TranslationParams): string;
  /**
   * zh-CN: 下载
   * zh-TW: 下載
   * en-US: Download
   */
  (key: "profile.menu.download", params?: TranslationParams): string;
  /**
   * zh-CN: 关于我
   * zh-TW: 關於我
   * en-US: About Me
   */
  (key: "profile.menu.aboutMe", params?: TranslationParams): string;
  /**
   * zh-CN: 无效的用户 ID
   * zh-TW: 無效的使用者 ID
   * en-US: Invalid User ID
   */
  (key: "profile.page.invalidUserId", params?: TranslationParams): string;
  /**
   * zh-CN: 最近播放歌曲
   * zh-TW: 最近播放歌曲
   * en-US: Recent Songs
   */
  (key: "profile.page.recentSongs", params?: TranslationParams): string;
  /**
   * zh-CN: 暂无播放记录
   * zh-TW: 暫無播放紀錄
   * en-US: No playback history available
   */
  (key: "profile.page.noRecentSongs", params?: TranslationParams): string;
  /**
   * zh-CN: 最近播放歌单
   * zh-TW: 最近播放歌單
   * en-US: Recent Playlists
   */
  (key: "profile.page.recentPlaylists", params?: TranslationParams): string;
  /**
   * zh-CN: 暂无歌单记录
   * zh-TW: 暫無歌單紀錄
   * en-US: No playlist records available
   */
  (key: "profile.page.noRecentPlaylists", params?: TranslationParams): string;
  /**
   * zh-CN: 公开歌单
   * zh-TW: 公開歌單
   * en-US: Public Playlists
   */
  (key: "profile.page.publicPlaylists", params?: TranslationParams): string;
  /**
   * zh-CN: 暂无公开歌单
   * zh-TW: 暫無公開歌單
   * en-US: No public playlists
   */
  (key: "profile.page.noPublicPlaylists", params?: TranslationParams): string;
  /**
   * zh-CN: {{count}} 首歌曲
   * zh-TW: {{count}} 首歌曲
   * en-US: {{count}} songs
   */
  (key: "profile.page.playlistSongCount", params?: TranslationParams): string;
  /**
   * zh-CN: 无法加载用户信息
   * zh-TW: 無法載入使用者資訊
   * en-US: Unable to load user information
   */
  (key: "profile.toast.loadUserFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 无法加载用户歌单
   * zh-TW: 無法載入使用者歌單
   * en-US: Unable to load user playlists
   */
  (key: "profile.toast.loadUserPlaylistsFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 获取专辑详情失败
   * zh-TW: 取得專輯詳情失敗
   * en-US: Failed to load album details
   */
  (key: "album.toast.fetchFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 未知专辑 ID
   * zh-TW: 未知專輯 ID
   * en-US: Unknown Album ID
   */
  (key: "album.empty.invalidId", params?: TranslationParams): string;
  /**
   * zh-CN: 请求的专辑不存在或暂时不可用
   * zh-TW: 請求的專輯不存在或暫時不可用
   * en-US: The requested album could not be found or is unavailable
   */
  (key: "album.empty.unavailable", params?: TranslationParams): string;
  /**
   * zh-CN: 未知年份
   * zh-TW: 未知年份
   * en-US: Unknown Year
   */
  (key: "album.meta.unknownYear", params?: TranslationParams): string;
  /**
   * zh-CN: 未知专辑
   * zh-TW: 未知專輯
   * en-US: Unknown Album
   */
  (key: "album.meta.unknownAlbum", params?: TranslationParams): string;
  /**
   * zh-CN: 未知歌手
   * zh-TW: 未知歌手
   * en-US: Unknown Artist
   */
  (key: "album.meta.unknownArtist", params?: TranslationParams): string;
  /**
   * zh-CN: 专辑
   * zh-TW: 專輯
   * en-US: Album
   */
  (key: "album.meta.type", params?: TranslationParams): string;
  /**
   * zh-CN: 在专辑中搜索...
   * zh-TW: 在專輯中搜尋...
   * en-US: Search in album...
   */
  (key: "album.searchPlaceholder", params?: TranslationParams): string;
  /**
   * zh-CN: 列表
   * zh-TW: 列表
   * en-US: List
   */
  (key: "album.listLabel", params?: TranslationParams): string;
  /**
   * zh-CN: {{count}} 首歌
   * zh-TW: {{count}} 首歌
   * en-US: {{count}} songs
   */
  (key: "album.totalSongs", params?: TranslationParams): string;
  /**
   * zh-CN: 专辑封面
   * zh-TW: 專輯封面
   * en-US: Album Cover
   */
  (key: "album.coverAlt", params?: TranslationParams): string;
  /**
   * zh-CN: 无效的歌手 ID
   * zh-TW: 無效的歌手 ID
   * en-US: Invalid Artist ID
   */
  (key: "artist.page.invalidId", params?: TranslationParams): string;
  /**
   * zh-CN: 已认证歌手
   * zh-TW: 已驗證歌手
   * en-US: Verified Artist
   */
  (key: "artist.hero.verified", params?: TranslationParams): string;
  /**
   * zh-CN: {{count}} 位听众
   * zh-TW: {{count}} 位聽眾
   * en-US: {{count}} listeners
   */
  (key: "artist.hero.listeners", params?: TranslationParams): string;
  /**
   * zh-CN: 简介
   * zh-TW: 簡介
   * en-US: About
   */
  (key: "artist.about.title", params?: TranslationParams): string;
  /**
   * zh-CN: {{count}} 月听众
   * zh-TW: {{count}} 月聽眾
   * en-US: {{count}} monthly listeners
   */
  (key: "artist.about.monthlyListeners", params?: TranslationParams): string;
  /**
   * zh-CN: 暂时没有这位歌手的简介。
   * zh-TW: 暫時沒有這位歌手的介紹。
   * en-US: No biography is available for this artist yet.
   */
  (key: "artist.about.noBio", params?: TranslationParams): string;
  /**
   * zh-CN: 热门歌曲
   * zh-TW: 熱門歌曲
   * en-US: Popular
   */
  (key: "artist.popular.title", params?: TranslationParams): string;
  /**
   * zh-CN: 暂无热门歌曲
   * zh-TW: 暫無熱門歌曲
   * en-US: No popular tracks yet
   */
  (key: "artist.popular.noTracks", params?: TranslationParams): string;
  /**
   * zh-CN: 作品
   * zh-TW: 作品
   * en-US: Discography
   */
  (key: "artist.discography.title", params?: TranslationParams): string;
  /**
   * zh-CN: 暂无专辑数据
   * zh-TW: 暫無專輯資料
   * en-US: No album data available
   */
  (key: "artist.discography.noAlbums", params?: TranslationParams): string;
  /**
   * zh-CN: 关注
   * zh-TW: 關注
   * en-US: Follow
   */
  (key: "artist.action.follow", params?: TranslationParams): string;
  /**
   * zh-CN: 已关注
   * zh-TW: 已關注
   * en-US: Following
   */
  (key: "artist.action.following", params?: TranslationParams): string;
  /**
   * zh-CN: 加载歌手数据失败
   * zh-TW: 載入歌手資料失敗
   * en-US: Failed to load artist data
   */
  (key: "artist.toast.fetchFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 专辑为空
   * zh-TW: 專輯為空
   * en-US: Album is empty
   */
  (key: "artist.toast.albumEmpty", params?: TranslationParams): string;
  /**
   * zh-CN: 加载专辑失败
   * zh-TW: 載入專輯失敗
   * en-US: Failed to load album
   */
  (key: "artist.toast.loadAlbumFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 已添加到喜欢的歌曲
   * zh-TW: 已加入喜歡的歌曲
   * en-US: Added to liked songs
   */
  (key: "artist.track.likedAdded", params?: TranslationParams): string;
  /**
   * zh-CN: 已从喜欢的歌曲中移除
   * zh-TW: 已從喜歡的歌曲中移除
   * en-US: Removed from liked songs
   */
  (key: "artist.track.likedRemoved", params?: TranslationParams): string;
  /**
   * zh-CN: 操作失败，请稍后再试
   * zh-TW: 操作失敗，請稍後再試
   * en-US: Operation failed. Please try again later.
   */
  (key: "artist.track.operationFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 歌曲已在队列中
   * zh-TW: 歌曲已在佇列中
   * en-US: Song is already in the queue
   */
  (key: "artist.track.queueExists", params?: TranslationParams): string;
  /**
   * zh-CN: 已添加到播放队列
   * zh-TW: 已加入播放佇列
   * en-US: Added to playback queue
   */
  (key: "artist.track.queueAdded", params?: TranslationParams): string;
  /**
   * zh-CN: 已添加到歌单
   * zh-TW: 已加入歌單
   * en-US: Added to playlist
   */
  (key: "artist.track.addToPlaylistSuccess", params?: TranslationParams): string;
  /**
   * zh-CN: 添加到歌单失败
   * zh-TW: 加入歌單失敗
   * en-US: Failed to add to playlist
   */
  (key: "artist.track.addToPlaylistFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 链接已复制到剪贴板
   * zh-TW: 連結已複製到剪貼簿
   * en-US: Link copied to clipboard
   */
  (key: "artist.track.copySuccess", params?: TranslationParams): string;
  /**
   * zh-CN: 复制链接失败
   * zh-TW: 複製連結失敗
   * en-US: Failed to copy link
   */
  (key: "artist.track.copyFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 晚上好
   * zh-TW: 晚上好
   * en-US: Good Night
   */
  (key: "home.greeting.night", params?: TranslationParams): string;
  /**
   * zh-CN: 早上好
   * zh-TW: 早安
   * en-US: Good Morning
   */
  (key: "home.greeting.morning", params?: TranslationParams): string;
  /**
   * zh-CN: 下午好
   * zh-TW: 下午好
   * en-US: Good Afternoon
   */
  (key: "home.greeting.afternoon", params?: TranslationParams): string;
  /**
   * zh-CN: 傍晚好
   * zh-TW: 傍晚好
   * en-US: Good Evening
   */
  (key: "home.greeting.evening", params?: TranslationParams): string;
  /**
   * zh-CN: 每日推荐
   * zh-TW: 每日推薦
   * en-US: Daily Recommendations
   */
  (key: "home.dailyRecommendations", params?: TranslationParams): string;
  /**
   * zh-CN: 刷新首页内容
   * zh-TW: 重新整理首頁內容
   * en-US: Refresh home content
   */
  (key: "home.refreshTitle", params?: TranslationParams): string;
  /**
   * zh-CN: 为 {{name}} 推荐
   * zh-TW: 為 {{name}} 推薦
   * en-US: Made for {{name}}
   */
  (key: "home.madeFor", params?: TranslationParams): string;
  /**
   * zh-CN: 你
   * zh-TW: 你
   * en-US: You
   */
  (key: "home.you", params?: TranslationParams): string;
  /**
   * zh-CN: 正在加载推荐...
   * zh-TW: 正在載入推薦...
   * en-US: Loading recommendations...
   */
  (key: "home.loadingRecommendations", params?: TranslationParams): string;
  /**
   * zh-CN: {{plays}} 播放 • 共 {{count}} 首
   * zh-TW: {{plays}} 播放 • 共 {{count}} 首
   * en-US: {{plays}} plays • {{count}} songs
   */
  (key: "home.playlistSummary", params?: TranslationParams): string;
  /**
   * zh-CN: 推荐歌手
   * zh-TW: 推薦歌手
   * en-US: Suggested Artists
   */
  (key: "home.suggestedArtists", params?: TranslationParams): string;
  /**
   * zh-CN: 你的收藏专辑
   * zh-TW: 你的收藏專輯
   * en-US: Your Collected Albums
   */
  (key: "home.yourCollectedAlbums", params?: TranslationParams): string;
  /**
   * zh-CN: 歌单为空
   * zh-TW: 歌單為空
   * en-US: Playlist is empty
   */
  (key: "home.toast.playlistEmpty", params?: TranslationParams): string;
  /**
   * zh-CN: 加载歌单失败
   * zh-TW: 載入歌單失敗
   * en-US: Failed to load playlist
   */
  (key: "home.toast.loadPlaylistFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 专辑为空
   * zh-TW: 專輯為空
   * en-US: Album is empty
   */
  (key: "home.toast.albumEmpty", params?: TranslationParams): string;
  /**
   * zh-CN: 加载专辑失败
   * zh-TW: 載入專輯失敗
   * en-US: Failed to load album
   */
  (key: "home.toast.loadAlbumFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 获取首页数据失败
   * zh-TW: 取得首頁資料失敗
   * en-US: Failed to load homepage data
   */
  (key: "home.toast.loadFailed", params?: TranslationParams): string;
  /**
   * zh-CN: 上一首
   * zh-TW: 上一首
   * en-US: Previous
   */
  (key: "tray.previous", params?: TranslationParams): string;
  /**
   * zh-CN: 下一首
   * zh-TW: 下一首
   * en-US: Next
   */
  (key: "tray.next", params?: TranslationParams): string;
  /**
   * zh-CN: 播放
   * zh-TW: 播放
   * en-US: Play
   */
  (key: "tray.play", params?: TranslationParams): string;
  /**
   * zh-CN: 暂停
   * zh-TW: 暫停
   * en-US: Pause
   */
  (key: "tray.pause", params?: TranslationParams): string;
  /**
   * zh-CN: 喜欢
   * zh-TW: 喜歡
   * en-US: Like
   */
  (key: "tray.like", params?: TranslationParams): string;
  /**
   * zh-CN: 取消喜欢
   * zh-TW: 取消喜歡
   * en-US: Unlike
   */
  (key: "tray.unlike", params?: TranslationParams): string;
  /**
   * zh-CN: 打开桌面歌词
   * zh-TW: 打開桌面歌詞
   * en-US: Open Desktop Lyrics
   */
  (key: "tray.openDesktopLyrics", params?: TranslationParams): string;
  /**
   * zh-CN: 设置
   * zh-TW: 設定
   * en-US: Settings
   */
  (key: "tray.settings", params?: TranslationParams): string;
  /**
   * zh-CN: 最小化
   * zh-TW: 最小化
   * en-US: Minimize
   */
  (key: "tray.minimize", params?: TranslationParams): string;
  /**
   * zh-CN: 退出
   * zh-TW: 退出
   * en-US: Exit
   */
  (key: "tray.exit", params?: TranslationParams): string;
  (key: TranslationKey, params?: TranslationParams): string;
}
