import type { FoliaCommandEntry } from "@/types/foliaCommands";

export const FOLIA_LYRIC_COMMANDS: Omit<FoliaCommandEntry, "path">[] = [
  {
    id: "folia-lyric-controls",
    parentId: "folia-settings",
    label: "歌词控制",
    summary: "歌词显示、翻译、罗马音与和声",
    keywords: "lyrics 歌词 字幕 翻译 和声",
    action: { kind: "group", group: "folia-lyric-controls" },
  },
  {
    id: "folia-lyric-overlay",
    parentId: "folia-lyric-controls",
    label: "显示底部歌词字幕",
    summary: "显示翻译、罗马音或接下来的歌词",
    keywords: "lyrics overlay display 显示 隐藏 字幕",
    action: { kind: "lyric-toggle", setting: "hideTranslationSubtitle", inverted: true },
  },
  {
    id: "folia-lyric-content-translation",
    parentId: "folia-lyric-controls",
    label: "翻译字幕",
    summary: "副行优先显示歌曲的翻译歌词",
    keywords: "translation 翻译 双语",
    action: { kind: "lyric-content", mode: "translation" },
  },
  {
    id: "folia-lyric-content-romanization",
    parentId: "folia-lyric-controls",
    label: "罗马音字幕",
    summary: "副行优先显示歌曲的罗马音",
    keywords: "romanization romaji 罗马音 注音",
    action: { kind: "lyric-content", mode: "romanization" },
  },
  {
    id: "folia-lyric-content-none",
    parentId: "folia-lyric-controls",
    label: "仅原文歌词",
    summary: "关闭翻译和罗马音，保留原文歌词预览",
    keywords: "original 原文 翻译 关闭",
    action: { kind: "lyric-content", mode: "none" },
  },
  {
    id: "folia-lyric-subtitle-background",
    parentId: "folia-lyric-controls",
    label: "字幕背景",
    summary: "为底部歌词字幕显示背景",
    keywords: "subtitle background 背景",
    action: { kind: "lyric-toggle", setting: "subtitleOverlayBackground" },
  },
  {
    id: "folia-lyric-harmony",
    parentId: "folia-lyric-controls",
    label: "显示和声字幕",
    summary: "在歌词包含伴唱时显示和声",
    keywords: "harmony background vocal 和声 伴唱",
    action: { kind: "lyric-toggle", setting: "showHarmonySubtitle" },
  },
  {
    id: "folia-lyric-harmony-background",
    parentId: "folia-lyric-controls",
    label: "和声字幕背景",
    summary: "为和声字幕显示背景",
    keywords: "harmony background 和声 背景",
    action: { kind: "lyric-toggle", setting: "harmonySubtitleBackground" },
  },
  {
    id: "folia-lyric-fonts",
    parentId: "folia-lyric-controls",
    label: "歌词字体与显示",
    summary: "调整字体、字号、透明度与歌词偏移",
    keywords: "font size opacity offset 字体 字号 透明度 偏移 延迟",
    action: { kind: "settings", section: "common" },
  },
  {
    id: "folia-lyric-details",
    parentId: "folia-lyric-controls",
    label: "字幕详细设置",
    summary: "调整字幕字体、字号与显示参数",
    keywords: "subtitle settings 字幕 字体 字号",
    action: { kind: "settings", section: "subtitle" },
  },
];
