app:
  gpuAcceleration: true
  devTools: true
  closeAction: 2
backend:
  port: 5252
  host: 127.0.0.1
  autoStart: true
frontend:
  devPort: 1515
  host: 127.0.0.1
logging:
  level: info
  format: "[{y}-{m}-{d} {h}:{i}:{s}.{ms}] [{level}] {text}"
  keepDays: 25
network:
  timeout: 5000
  max_retries: 5
  retry_delay: 1000
  randomCNIP: false
