import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { messages, type TranslationKey } from "../lib/i18n";

const locales = ["zh-CN", "zh-TW", "en-US"] as const;
const keys = Object.keys(messages["zh-CN"]) as TranslationKey[];

const escapeDoc = (value: string) =>
  value.replace(/\*\//g, "*\\/").replace(/\r?\n/g, "\\n");

const lines = [
  "// This file is auto-generated by script/generate-i18n-types.ts.",
  "// Do not edit manually.",
  "",
  'import type { TranslationKey, TranslationParams } from "@/lib/i18n";',
  "",
  "export interface TranslateFn {",
];

for (const key of keys) {
  lines.push("  /**");
  for (const locale of locales) {
    lines.push(`   * ${locale}: ${escapeDoc(messages[locale][key])}`);
  }
  lines.push("   */");
  lines.push(`  (key: ${JSON.stringify(key)}, params?: TranslationParams): string;`);
}

lines.push("  (key: TranslationKey, params?: TranslationParams): string;");
lines.push("}");
lines.push("");

const outputPath = resolve(process.cwd(), "types", "i18n.generated.d.ts");
writeFileSync(outputPath, `${lines.join("\n")}\n`, "utf8");

console.log(`Generated ${outputPath}`);
